config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :categories, only: [:index, :new, :create, :destroy] do
    resources :expenses, only: [:index, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  # root "articles#index"

  devise_scope :user do

    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
  
    unauthenticated do
      root "home#index", as: :unauthenticated_root
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true, length: { maximum: 500 }

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :expenses, foreign_key: 'author_id'
  has_many :categories

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:full_name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:full_name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.new
  end

  def index
    @categories = Category.created_by_current_user(current_user)
  end

  def create
    return if params[:category][:icon].match(/\A[^A-Za-z0-9]+\z/)

    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new, alert: 'Error, Category not created'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def new
    @expense = Expense.new
    @categories = Category.created_by_current_user(current_user)
  end

  def index
    @expenses = Expense.joins(:categories).where(categories: { id: params[:category_id] }).order(created_at: :desc)
    @category = Category.find(params[:category_id])
  end

  def create
    params = expense_params
    @expense = Expense.new(name: params[:name], amount: params[:amount])
    @expense.author = current_user
    @categories_id = params[:ids]

    @categories_id.each do |id|
      category = Category.find(id) unless id == ''
      @expense.categories.push(category) unless category.nil?
    end

    return :new unless @expense.categories.any?

    if @expense.save
      redirect_to category_expenses_path(@expense.categories.first.id), notice: 'Expenses added successfully'
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, ids: [])
  end

  def create_general_category
    @general = current_user.categories.where(name: 'General').first

    if @general.nil?
      @general = Category.create(name: 'General',
                                 icon: 'https://cdn-icons-png.flaticon.com/512/3418/3418001.png', author: current_user)
    end

    @general
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/index.html.erb
<div class="categories-main-div">
    <h2 class="category-main-title">All categories</h2>
    <% if @categories.empty? %>
    <div class="empty-category">
        <h3>You have not added any category yet</h3>
        <%= link_to 'Add Category', new_category_path %>
    </div>
    <% else %>
        <div class="categories-section">
            <% @categories.each do |category| %>
                <div class="category-section">
                    <div>
                        <%= image_tag(category.icon || '', class: "category_image") %>
                    </div>
                    <div class="category-name-div">
                        <%= link_to category.name, category_expenses_path(category), class: 'category-name' %>
                        <span>
                            <%= category.created_at.strftime("%d %b %Y") %>
                        </span>
                    </div>
                    <div class="category-total-amount">
                        <Span>
                            $<%= category.expenses.inject(0) { |sum, e| sum += e.amount  }%> 
                        </Span>
                    </div>
                </div>
            <% end %>
            <%= link_to 'Add Category', new_category_path, class: 'add-new-category-btn' %>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<%= render "shared/back" %>
<div class="category-new">
    <h2>New Category</h2>

    <%= form_with(model: Category, url: categories_path, method: :post, class: 'create-new-category-form') do |f| %>

        <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, placeholder: "Enter category's name" %>
        </div>

        <div class="field">
            <%= f.label :icon %>
            <%= f.text_field :icon, placeholder: 'Paste icon url'%>
        </div>


        <%= f.submit 'Save', class: 'Submit-btn' %> <br>
    <% end %>
</div>

app/views/expenses/index.html.erb
<%= render "shared/back" %>
<div class="expenses-main-div">
    <h3 class="expenses-main-title">Expenses</h3>
        <% if @expenses.empty? %>
            <div class="empty-expenses">
                <h3>You have not added any Expenses yet to the <%= @category.name %> Category</h3>
                <%= link_to 'Add new expenses', new_category_expense_path %>
            </div>
        <% else %>
            <div class="expenses-category-total">
                <span class="ex-cat-name">
                    <%= @category.name %>
                </span>
                <Span>
                    $<%= @expenses.inject(0) { |sum, e| sum += e.amount  }%> 
                </Span>
            </div>
            <div class="expenses-section">
                <% @expenses.each do |expense| %>
                    <div class="expense-section">
                        <div>
                            <%= image_tag(@category.icon || '', class: "expenses_image") %>
                        </div>
                        <div  class="expenses-name-div">
                            <h2>
                                <%= expense.name %>
                            </h2>
                            <span>
                                <%= expense.created_at.strftime("%d %b %Y") %>
                            </span>
                        </div>
                        <div  class="expenses-total-amount">
                            <Span>
                                $<%= expense.amount %> 
                            </Span>
                        </div>
                    </div>
                <% end %>
            </div>
        <%= link_to 'Add new expenses', new_category_expense_path, class: 'add-new-expense-btn' %>
    <% end %>

</div>

app/views/expenses/new.html.erb
<%= render "shared/back" %>

<div  class="expense-new">
    <h2>Add new Expenses</h2>

    <%= form_with(model: Expense, url: category_expenses_path, method: :post, class: 'create-new-expense-form') do |f| %>
            
        <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, placeholder: 'Enter Expenses name', class: 'name-input' %>
        </div>

        <div class="field">
            <%= f.label :amount %>
            <%= f.number_field :amount, step: 1, placeholder: 'How much did you spend', class: 'amount-input'  %>
        </div>

            <% if @categories %>
                <div class="cat-select-field">
                    <%= f.label :categories %>
                    <%= f.collection_check_boxes(:ids, @categories, :id, :name) do |b| %>
                        <div class="checkbox">
                        <%= b.check_box + b.label %>
                        </div>
                    <% end %>
                    </div>
            <% end %>

            <%= f.submit 'Save', class: 'Submit-expense-btn' %>

    <% end %>
</div>

app/views/home/index.html.erb
<div class="splash-main-div">
    <h1 class="main-title">Budget Buddy</h1>
    <h2>Welcome</h2>
    <div class="splash-btns">
        <%= link_to 'Sign up', new_user_registration_path, class: 'nav-sign-up-btn' %>
        <%= link_to 'Sign in',  new_user_session_path, class: 'nav-sign-in-btn' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_back.html.erb
<a href="/" class="back-btn-div">
    <%= image_tag 'icons8-left-arrow-30.png', class: 'back-btn' %>
    <span>Back</span>
</a>

app/views/shared/_navbar.html.erb
<nav class="nav-bar">
    <div class="nav-bar-div">
        <%= image_tag 'icons8-menu-rounded-50.png', class: 'harmburger-menu' %>
        <div>
            <% if user_signed_in? %>
                <span><%= link_to 'Categories', "/", class: 'home-btn' %></span>
            <% else %>
                <span><%= link_to 'Home', "/", class: 'home-btn' %></span>
            <% end %>
        </div>
        <div class="profile-section">
            <% if user_signed_in? %>
                <h3>
                    Hey <span><%= current_user.full_name%></span>
                </h3>
                <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-sign-out-btn' %>
            <% end %>
        </div>
    </div>
</nav>

